### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by ckgathi** [Copyleaks/Python-Plagiarism-Checker#1]
How do i check plagiarism between 2 local files or i have to upload files in my online account so it check a local file against whats uploaded on the copyleaks website?

language python

**Comment by Copyleaks** [comment]
Hi Ckgathi, 

Currently a scan of two local files for plagiarism through the API is not available. It is abailable through the website,  with our comparison tool, but not through the API.

Thanks,
The Copyleaks Team
