### ISSUE TITLE
How to set `properties.aiGeneratedText.detect`  via Python API?

### ISSUE THREAD

**Issue by mnelson4** [Copyleaks/Python-Plagiarism-Checker#17]
Hi I'd like to enable the[ `properties.aiGeneratedText.detect` scan property ](https://api.copyleaks.com/documentation/v3/scans/submit/file)but don't see a method for doing that in the Python API.
It seems like the Python library needs to be updated

**Comment by AihamAR** [comment]
Hey,
You can use this property now with the new version https://pypi.org/project/copyleaks/4.0.0/ .

**Comment by mnelson4** [comment]
🎸! Thanks
