### ISSUE TITLE
Error while fetching result

### ISSUE THREAD

**Issue by arkangel1611** [Copyleaks/Python-Plagiarism-Checker#2]
Traceback (most recent call last):
  File "copyleaks.py", line 45, in <module>
    print('Title: %s' % (result.getTitle()))
AttributeError: 'ResultRecord' object has no attribute 'getTitle'

Any idea why i m getting this error... just wanted to try how well this api works

**Comment by Copyleaks** [comment]
Hi,

This issue is solved on Version 2.4 and up.

Thanks,
The Copyleaks Team
