### ISSUE TITLE
How to test CopyLeaks V3 API AI detector `properties.aiGeneratedText.detect`

### ISSUE THREAD

**Issue by PhiBangKimNguyen** [Copyleaks/Python-Plagiarism-Checker#20]
Hi Copyleaks team,

I currently use the older Copyleaks API v1 and want to switch to the newer API v3. Since I implemented `properties.aiGeneratedText.detect` to True, I have no way of verifying that whether the Sandbox account support this new feature, making it harder for testing purposes. I would appreciate your help and clarification on this matter.

**Comment by AihamAR** [comment]
Hey @PhiBangKimNguyen,

The sandbox feature doesn't support the ai generated text feature.
But we suggest you take an AI text and try it on the production environment then save the completed webhook and use it for testing.

**Comment by PhiBangKimNguyen** [comment]
Thank you for your response. One more question regarding the JavaScript update for Copyleaks V3. We've been using the old V1 JavaScript for Plagiarism Report (https://github.com/Copyleaks/plagiarism-report). Will the lastest JavaScript for Plagiarism Report work with the new AI detector features? What can we update on?

**Comment by AihamAR** [comment]
@PhiBangKimNguyen  Please move this question to the relevant repository https://github.com/Copyleaks/plagiarism-report
